import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import { Poppins } from "next/font/google";
import "./ui/globals.css";
import type { Metadata } from "next";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning className={`h-full`}>
      <body className={`${poppins.variable} h-full`}>
        <Theme
          accentColor="cyan"
          grayColor="gray"
          appearance="dark"
          className="h-full">
          {children}
        </Theme>
      </body>
    </html>
  );
}
